export const GET_DATA_REQUEST = "GET_DATA_REQUEST";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_DATA_ERROR = "GET_DATA_ERROR";


export const ADD_DATA_REQUEST = "ADD_DATA_REQUEST";
export const ADD_DATA_SUCCESS = "ADD_DATA_SUCCESS";
export const ADD_DATA_ERROR = "ADD_DATA_ERROR";


export const DELETE_DATA_REQUEST = "DELETE_DATA_REQUEST";
export const DELETE_DATA_SUCCESS = "DELETE_DATA_SUCCESS";
export const DELETE_DATA_ERROR = "DELETE_DATA_ERROR";


export const STATUS_DATA_REQUEST = "STATUS_DATA_REQUEST";
export const STATUS_DATA_SUCCESS = "STATUS_DATA_SUCCESS";
export const STATUS_DATA_ERROR = "STATUS_DATA_ERROR";


export const UPDATE_DATA_REQUEST = "UPDATE_DATA_REQUEST";
export const UPDATE_DATA_SUCCESS = "UPDATE_DATA_SUCCESS";
export const UPDATE_DATA_ERROR = "UPDATE_DATA_ERROR";

export const POST_TO_CART ="POST_TO_CART";

export const GET_THE_CART="GET_THE_CART";

export const DELETE_CART_ITEM ="DELETE_CART_ITEM";
  
